spring:
    cache:
        redis:
            time-to-live: 1200000
        type: redis
    datasource:
        password: nbmax32$ #${stage.oracle.ifw_owner.ifw_app.password}
        tomcat:
            max-active: 5
            max-wait: 10000
            test-on-borrow: true
        url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=ipspv-stgstl.mastercard.int)(PORT=1527)))(CONNECT_DATA=(SERVICE_NAME=pv_ifdatasource)))
        username: ifw_app
