spring:
    cache:
        redis:
            time-to-live: 7200000
        type: redis
    datasource:
        password: ${mtf.stl.oracle.ifw_owner.ifw_app.password}
        tomcat:
            max-active: 5
            max-wait: 10000
            test-on-borrow: true
        url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=IPSPV-MTFSTL.mastercard.int)(PORT=1527)))(CONNECT_DATA=(SERVICE_NAME=pv_online_serv)))
        username: ifw_app
